use lazy_static::lazy_static;
use regex::{Regex, RegexSet};
use serde::{Deserialize, Serialize};

/// 风险严重程度
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Severity {
    Low,
    Medium,
    High,
    Critical,
}

/// 风险类别
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Category {
    Destructive,         // 破坏性操作
    RemoteExec,          // 远程执行
    CmdInjection,        // 命令注入
    Network,             // 网络外传
    Privilege,           // 权限提升
    Secrets,             // 敏感泄露
    Persistence,         // 持久化
    SensitiveFileAccess, // 敏感文件访问
}

/// 置信度等级
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Confidence {
    High,   // 高置信度，误报可能性低
    Medium, // 中等置信度
    Low,    // 低置信度，可能误报
}

/// 危险模式规则
#[derive(Debug, Clone)]
pub struct PatternRule {
    pub id: &'static str,
    pub name: &'static str,
    pub pattern: Regex,
    pub severity: Severity,
    pub category: Category,
    pub weight: i32,
    pub description: &'static str,
    pub hard_trigger: bool,
    pub confidence: Confidence,       // 新增
    pub remediation: &'static str,    // 新增：修复建议
    pub cwe_id: Option<&'static str>, // 新增：CWE 编号
}

impl PatternRule {
    fn new(
        id: &'static str,
        name: &'static str,
        pattern: &'static str,
        severity: Severity,
        category: Category,
        weight: i32,
        description: &'static str,
        hard_trigger: bool,
        confidence: Confidence,       // 新增
        remediation: &'static str,    // 新增
        cwe_id: Option<&'static str>, // 新增
    ) -> Self {
        Self {
            id,
            name,
            pattern: Regex::new(pattern).expect("Invalid regex pattern"),
            severity,
            category,
            weight,
            description,
            hard_trigger,
            confidence,  // 新增
            remediation, // 新增
            cwe_id,      // 新增
        }
    }
}

lazy_static! {
    /// 所有危险模式规则库
    pub static ref PATTERN_RULES: Vec<PatternRule> = vec![
        // A. 破坏性操作
        PatternRule::new(
            "RM_RF_ROOT",
            "删除根目录",
            r"rm\s+(?:-[a-zA-Z]*\s+)*(?:-[a-zA-Z]*[rR][a-zA-Z]*\s+(?:-[a-zA-Z]*\s+)*/(?:$|\s|;|\|)|/\s+(?:-[a-zA-Z]*\s+)*-[a-zA-Z]*[rR][a-zA-Z]*(?:\s|;|\||$))",
            Severity::Critical,
            Category::Destructive,
            100,
            "rm -rf / 删除根目录",
            true,
            Confidence::High,
            "检查命令参数，避免操作根目录或使用通配符",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "RM_RF_HOME",
            "删除用户目录",
            r#"rm\s+(?:-[a-zA-Z]*\s+)*(?:-[a-zA-Z]*[rR][a-zA-Z]*\s+(?:-[a-zA-Z]*\s+)*(?:'|")?(~|\$HOME|\$\{HOME\})(?:'|")?/?(?:\s|;|\||$)|(?:'|")?(~|\$HOME|\$\{HOME\})(?:'|")?/?\s+(?:-[a-zA-Z]*\s+)*-[a-zA-Z]*[rR][a-zA-Z]*(?:\s|;|\||$))"#,
            Severity::Critical,
            Category::Destructive,
            90,
            "rm -rf ~ 删除用户目录",
            true,
            Confidence::High,
            "检查命令参数，避免操作用户主目录",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "RM_RF_HOME_GLOB",
            "清空用户目录内容",
            r#"rm\s+(?:-[a-zA-Z]*\s+)*(?:-[a-zA-Z]*[rR][a-zA-Z]*\s+(?:-[a-zA-Z]*\s+)*(?:'|")?(~|\$HOME|\$\{HOME\})(?:'|")?/\*(?:\s|;|\||$)|(?:'|")?(~|\$HOME|\$\{HOME\})(?:'|")?/\*\s+(?:-[a-zA-Z]*\s+)*-[a-zA-Z]*[rR][a-zA-Z]*(?:\s|;|\||$))"#,
            Severity::Critical,
            Category::Destructive,
            95,
            "rm -rf ~/* 清空用户目录内容",
            true,
            Confidence::High,
            "检查命令参数，避免清空用户主目录内容",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "RM_HOME_GLOB",
            "疑似清空用户目录内容",
            r#"rm\s+(?:-[a-qs-zA-QS-Z]*\s+)*(?:'|")?(~|\$HOME|\$\{HOME\})(?:'|")?/\*(?:\s|;|\||$)"#,
            Severity::High,
            Category::Destructive,
            50,
            "rm ~/* 可能清空用户目录内容",
            false,
            Confidence::Low,
            "确认命令参数，避免误删用户主目录内容",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "RM_RF_USERS_HOME",
            "删除macOS用户目录",
            r#"rm\s+(?:-[a-zA-Z]*\s+)*(?:-[a-zA-Z]*[rR][a-zA-Z]*\s+(?:-[a-zA-Z]*\s+)*(?:'|")?/Users/[^/\s]+(?:'|")?/?(?:\s|;|\||$)|(?:'|")?/Users/[^/\s]+(?:'|")?/?\s+(?:-[a-zA-Z]*\s+)*-[a-zA-Z]*[rR][a-zA-Z]*(?:\s|;|\||$))"#,
            Severity::Critical,
            Category::Destructive,
            95,
            "rm -rf /Users/<name> 删除macOS用户目录",
            true,
            Confidence::High,
            "检查命令参数，避免操作macOS用户主目录",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "DD_WIPE",
            "磁盘擦除",
            r"dd\s+.*of=/dev/(sd[a-z]|nvme|hd[a-z]|vd[a-z]|r?disk\d+(s\d+)?)",
            Severity::Critical,
            Category::Destructive,
            100,
            "dd 写入磁盘设备",
            true,
            Confidence::High,
            "检查命令参数，避免写入系统磁盘设备",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "MKFS_FORMAT",
            "格式化磁盘",
            r"mkfs(\.[a-z0-9]+)?\s+/dev/",
            Severity::Critical,
            Category::Destructive,
            100,
            "mkfs 格式化命令",
            true,
            Confidence::High,
            "检查命令参数，避免格式化系统磁盘",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "DISKUTIL_ERASE",
            "diskutil擦除磁盘",
            r"diskutil\s+erase(Disk|Volume)\b",
            Severity::Critical,
            Category::Destructive,
            100,
            "diskutil eraseDisk/eraseVolume 擦除磁盘",
            true,
            Confidence::High,
            "检查diskutil擦除操作，避免误擦系统磁盘",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "NEWFS_FORMAT",
            "newfs格式化",
            r"newfs(\.[a-z0-9]+)?\s+.*?/dev/r?disk\d+(s\d+)?",
            Severity::Critical,
            Category::Destructive,
            100,
            "newfs 格式化命令",
            true,
            Confidence::High,
            "检查newfs操作，避免格式化系统磁盘",
            Some("CWE-78"),
        ),

        // B. 远程执行
        PatternRule::new(
            "CURL_PIPE_SH",
            "Curl管道执行",
            // 说明：为了降低误报（例如在 console.error/README 中仅打印安装指令），
            // 这里把“硬阻止”的匹配收紧为“疑似实际执行场景”——要么是 shell 脚本里直接以 curl 开头，
            // 要么同一行出现常见的进程执行 API（execSync/os.system/subprocess 等）再跟随 curl|sh。
            r"(?i)(?:^\s*curl\s+[^|]*?\|\s*(?:ba)?sh\b|\b(?:execSync|exec|spawnSync|spawn|execFileSync|execFile|os\.system|subprocess\.|Runtime\.getRuntime\(\)\.exec|ProcessBuilder|exec\.Command|Command::new)\b[^\r\n]{0,200}?curl\s+[^|]*?\|\s*(?:ba)?sh\b)",
            Severity::Critical,
            Category::RemoteExec,
            90,
            "curl | sh 远程执行",
            true,
            Confidence::High,
            "避免直接执行远程脚本，应先下载后检查",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "CURL_PIPE_SH_MENTION",
            "Curl管道执行（疑似文本/字符串）",
            r"(?i)curl\s+[^|]*?\|\s*(?:ba)?sh\b",
            Severity::Low,
            Category::RemoteExec,
            0,
            "curl | sh 出现在文本/字符串中（未确认实际执行）",
            false,
            Confidence::Low,
            "如果这段命令会被执行，应改为先下载再校验/审查；若仅为说明文字，可忽略此提示",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "WGET_PIPE_SH",
            "Wget管道执行",
            r"wget\s+[^|]*?\|\s*(ba)?sh",
            Severity::Critical,
            Category::RemoteExec,
            90,
            "wget | sh 远程执行",
            true,
            Confidence::High,
            "避免直接执行远程脚本，应先下载后检查",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "BASE64_EXEC",
            "Base64解码执行",
            r"base64\s+(?:-d|--decode)[^|]*?\|\s*(ba)?sh",
            Severity::Critical,
            Category::RemoteExec,
            85,
            "base64 解码后执行",
            true,
            Confidence::High,
            "避免执行Base64编码的命令，可能隐藏恶意代码",
            Some("CWE-506"),
        ),
        PatternRule::new(
            "REVERSE_SHELL",
            "反弹Shell",
            r"(?i)(\b(ba)?sh\b.*?/dev/(tcp|udp)/|/dev/(tcp|udp)/.*\b(ba)?sh\b|\b(nc|ncat)\b.*\s-e\s+(/bin/)?(ba)?sh\b|\bsocat\b.*\bexec:(/bin/)?(ba)?sh\b|\bpython[23]?\b[^\r\n]*-c[^\r\n]*socket[^\r\n]*connect|\bperl\b[^\r\n]*-e[^\r\n]*socket[^\r\n]*connect)",
            Severity::Critical,
            Category::RemoteExec,
            95,
            "反弹Shell后门",
            true,
            Confidence::High,
            "检查网络连接和进程调用，避免反弹Shell后门",
            Some("CWE-506"),
        ),
        PatternRule::new(
            "POWERSHELL_ENCODED_COMMAND",
            "PowerShell 编码命令",
            r"(?i)\b(?:powershell|pwsh)(?:\.exe)?\b[^\r\n]*?(?:-enc(?:odedcommand)?|-e)\s+[A-Za-z0-9+/=]{20,}",
            Severity::Critical,
            Category::RemoteExec,
            90,
            "PowerShell -EncodedCommand 编码执行",
            true,
            Confidence::High,
            "避免执行编码后的PowerShell命令，必须先审查解码内容",
            Some("CWE-506"),
        ),
        PatternRule::new(
            "POWERSHELL_IEX_DOWNLOAD",
            "PowerShell 下载后执行",
            r"(?i)\b(?:IEX|Invoke-Expression)\b[^\r\n]*?(?:DownloadString|DownloadFile|Invoke-WebRequest|iwr|curl|wget|WebClient)",
            Severity::Critical,
            Category::RemoteExec,
            95,
            "PowerShell IEX/Invoke-Expression 下载后执行",
            true,
            Confidence::High,
            "禁止下载后直接执行PowerShell脚本，应先下载审查",
            Some("CWE-506"),
        ),
        PatternRule::new(
            "POWERSHELL_PIPE_IEX",
            "PowerShell 管道执行",
            r"(?i)\b(?:Invoke-WebRequest|iwr|curl|wget)\b[^\r\n]*?\|\s*(?:IEX|Invoke-Expression)\b",
            Severity::Critical,
            Category::RemoteExec,
            95,
            "PowerShell IWR/IEX 管道执行",
            true,
            Confidence::High,
            "禁止通过管道直接执行远程内容",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "MSHTA_EXEC",
            "MSHTA 脚本执行",
            r"(?i)\bmshta(?:\.exe)?\b[^\r\n]*?(?:https?://|javascript:|vbscript:)",
            Severity::Critical,
            Category::RemoteExec,
            95,
            "mshta 远程或脚本执行",
            true,
            Confidence::High,
            "避免使用mshta执行远程脚本",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "REGSVR32_SCJ",
            "Regsvr32 Scriptlet 执行",
            r"(?i)\bregsvr32(?:\.exe)?\b[^\r\n]*?(?:/i:\s*https?://|scrobj\.dll)",
            Severity::Critical,
            Category::RemoteExec,
            95,
            "regsvr32 通过脚本组件执行远程内容",
            true,
            Confidence::High,
            "避免使用regsvr32加载远程脚本组件",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "RUNDLL32_SCRIPT",
            "Rundll32 脚本执行",
            r"(?i)\brundll32(?:\.exe)?\b[^\r\n]*?(?:javascript:|vbscript:|https?://)",
            Severity::Critical,
            Category::RemoteExec,
            95,
            "rundll32 执行脚本或远程内容",
            true,
            Confidence::High,
            "避免使用rundll32执行脚本或远程内容",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "BITSADMIN_TRANSFER",
            "Bitsadmin 传输",
            r"(?i)\bbitsadmin(?:\.exe)?\b[^\r\n]*?(?:/transfer|/addfile|/setnotifycmdline)",
            Severity::Medium,
            Category::RemoteExec,
            45,
            "bitsadmin 下载/执行链路",
            false,
            Confidence::Medium,
            "检查bitsadmin用途，避免用于下载恶意内容",
            Some("CWE-494"),
        ),
        PatternRule::new(
            "CERTUTIL_DOWNLOAD",
            "Certutil 下载/解码",
            r"(?i)\bcertutil(?:\.exe)?\b[^\r\n]*?(?:-urlcache|-decode|-encode|-split)",
            Severity::Medium,
            Category::RemoteExec,
            45,
            "certutil 可用于下载/解码payload",
            false,
            Confidence::Medium,
            "避免使用certutil下载或解码可疑内容",
            Some("CWE-494"),
        ),
        PatternRule::new(
            "WMIC_PROCESS_CREATE",
            "WMIC 进程创建",
            r"(?i)\bwmic\b[^\r\n]*?\bprocess\b[^\r\n]*?\bcall\b[^\r\n]*?\bcreate\b",
            Severity::Medium,
            Category::RemoteExec,
            40,
            "wmic process call create 进程执行",
            false,
            Confidence::Medium,
            "审查wmic进程创建行为，避免执行可疑命令",
            Some("CWE-78"),
        ),

        // C. 命令注入
        PatternRule::new(
            "PY_EVAL",
            "eval() 动态执行",
            r"(?:^|[^\w.])eval\s*\(",
            Severity::Low,
            Category::CmdInjection,
            6,
            "eval() 动态执行",
            false,
            Confidence::Low,  // 降低置信度，因为可能误报JS/TS
            "避免使用eval()动态执行代码，使用安全的替代方法",
            Some("CWE-94"),
        ),
        PatternRule::new(
            "PY_EXEC",
            "Python exec",
            r"(?:^|[^\w.])exec\(",
            Severity::Low,
            Category::CmdInjection,
            6,
            "exec() 动态执行",
            false,
            Confidence::Medium,
            "避免使用exec()动态执行代码，使用安全的替代方法",
            Some("CWE-94"),
        ),
        PatternRule::new(
            "OS_SYSTEM",
            "os.system",
            r"os\.system\s*\(",
            Severity::Low,
            Category::CmdInjection,
            6,
            "os.system() Shell执行",
            false,
            Confidence::Medium,
            "避免使用os.system()，改用subprocess.run()并设置shell=False",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "SUBPROCESS_SHELL",
            "subprocess shell=True",
            r"subprocess\.(run|call|Popen)\s*\([^)]*shell\s*=\s*True",
            Severity::Low,
            Category::CmdInjection,
            6,
            "subprocess shell=True",
            false,
            Confidence::High,
            "避免设置shell=True，使用列表参数传递命令",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "SUBPROCESS_CALL",
            "subprocess 调用",
            r"subprocess\.(run|call|Popen)\s*\(",
            Severity::Low,
            Category::CmdInjection,
            0,
            "subprocess 进程调用",
            false,
            Confidence::Low,
            "确保命令参数经过验证，避免注入风险",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "CMD_WRAPPER",
            "CMD 包装执行",
            r"(?i)\b(?:cmd(?:\.exe)?)\s+/[ck]\s+.*?\b(?:powershell|pwsh|mshta|wscript|cscript|rundll32|regsvr32)\b",
            Severity::Medium,
            Category::CmdInjection,
            35,
            "cmd /c 包装危险程序执行",
            false,
            Confidence::Medium,
            "避免使用cmd包装执行高风险程序",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "POWERSHELL_BYPASS_POLICY",
            "PowerShell 规避策略",
            r"(?i)\b(?:powershell|pwsh)(?:\.exe)?\b[^\r\n]*?(?:-executionpolicy\s+bypass|-ep\s+bypass|-windowstyle\s+hidden|-w\s+hidden)",
            Severity::Medium,
            Category::CmdInjection,
            30,
            "PowerShell 规避执行策略/隐藏窗口",
            false,
            Confidence::Medium,
            "审查PowerShell执行参数，避免规避策略",
            Some("CWE-693"),
        ),

        // D. 网络外传
        PatternRule::new(
            "CURL_POST",
            "Curl POST",
            r"curl\s+[^;|]*-X\s*POST",
            Severity::Low,
            Category::Network,
            6,
            "curl POST 请求",
            false,
            Confidence::Medium,
            "确认网络请求目标，避免泄露敏感数据",
            Some("CWE-319"),
        ),
        PatternRule::new(
            "NETCAT",
            "Netcat连接",
            r"\bnc\s+(-[a-z]*\s+)*[a-zA-Z0-9.-]+\s+\d+",
            Severity::Low,
            Category::Network,
            6,
            "netcat 网络连接",
            false,
            Confidence::Medium,
            "检查netcat使用场景，避免未授权的网络连接",
            Some("CWE-319"),
        ),
        PatternRule::new(
            "PY_URLLIB",
            "Python urllib",
            r"urllib\.request\.urlopen\s*\(",
            Severity::Low,
            Category::Network,
            3,
            "urllib 网络请求",
            false,
            Confidence::Low,
            "确认请求目标URL的安全性，使用HTTPS协议",
            None,
        ),
        PatternRule::new(
            "HTTP_REQUEST",
            "HTTP 请求库",
            r"requests\.(get|post|put|delete|patch)\s*\(",
            Severity::Low,
            Category::Network,
            3,
            "Python requests HTTP 请求",
            false,
            Confidence::Low,
            "确认请求目标URL的安全性，使用HTTPS协议",
            None,
        ),

        // E. 权限提升
        PatternRule::new(
            "SUDO",
            "sudo提权",
            r"\bsudo\s+",
            Severity::Low,
            Category::Privilege,
            3,  // 降低weight，因为sudo在正常脚本中很常见
            "sudo 权限提升",
            false,
            Confidence::Low,
            "审查sudo使用场景，确保符合最小权限原则",
            Some("CWE-250"),
        ),
        PatternRule::new(
            "CHMOD_777",
            "chmod 777",
            r"chmod\s+(?:-[a-zA-Z]*\s+)*(?:[0-7]?[0-7][67][67]|(?:a|ugo|o)?[+=]rwx|(?:a|ugo|o)\+[rwx]*w)",
            Severity::High,
            Category::Privilege,
            55,
            "chmod 设置过于开放的权限（world-writable）",
            false,
            Confidence::High,
            "避免设置world-writable权限，使用最小权限原则",
            Some("CWE-732"),
        ),
        PatternRule::new(
            "SUDOERS",
            "sudoers修改",
            r"(/etc/sudoers(?:\.d(?:/\S+)?)?|visudo|NOPASSWD)",
            Severity::Critical,
            Category::Privilege,
            95,
            "sudoers 文件修改",
            true,
            Confidence::High,
            "检查sudoers修改，避免不当的权限配置",
            Some("CWE-250"),
        ),

        // F. 持久化
        PatternRule::new(
            "CRONTAB",
            "Crontab持久化",
            r"(crontab\s+-[^l\s]|/etc/cron\.(d|daily|hourly|weekly|monthly)/)",
            Severity::High,
            Category::Persistence,
            65,
            "crontab 持久化（排除只读操作）",
            false,
            Confidence::Medium,
            "检查定时任务内容，避免恶意持久化机制",
            Some("CWE-506"),
        ),
        PatternRule::new(
            "SSH_KEYS",
            "SSH密钥注入",
            r"(>>|>)\s*\S*\.ssh/(?:authorized_keys|id_)",
            Severity::Critical,
            Category::Persistence,
            90,
            "SSH 密钥写入",
            true,
            Confidence::High,
            "检查SSH密钥写入操作，避免未授权访问",
            Some("CWE-506"),
        ),
        PatternRule::new(
            "REG_RUN_KEY_ADD",
            "注册表 Run 持久化",
            r"(?i)\breg(\.exe)?\s+add\s+HK(LM|CU)\\Software\\Microsoft\\Windows\\CurrentVersion\\Run(Once|OnceEx)?\b",
            Severity::High,
            Category::Persistence,
            70,
            "注册表 Run/RunOnce 持久化",
            false,
            Confidence::High,
            "审查注册表启动项写入，避免持久化植入",
            None,
        ),
        PatternRule::new(
            "POWERSHELL_RUN_KEY",
            "PowerShell 注册表启动项",
            r"(?i)\b(New-ItemProperty|Set-ItemProperty)\b[^\r\n]*(HK(LM|CU):\\Software\\Microsoft\\Windows\\CurrentVersion\\Run(Once|OnceEx)?)",
            Severity::High,
            Category::Persistence,
            70,
            "PowerShell 写入 Run/RunOnce 启动项",
            false,
            Confidence::Medium,
            "审查 PowerShell 注册表写入，避免持久化",
            None,
        ),
        PatternRule::new(
            "STARTUP_FOLDER_PERSISTENCE",
            "Startup 文件夹持久化",
            r"(?i)\b(copy|xcopy|robocopy|move|mkdir|md|echo|type|new-item|set-content|add-content|out-file|copy-item|move-item)\b[^\r\n]*(\\Microsoft\\Windows\\Start Menu\\Programs\\Startup|\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Startup|shell:startup|shell:common startup)|>\s*[^\r\n]*(\\Microsoft\\Windows\\Start Menu\\Programs\\Startup|\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Startup)",
            Severity::High,
            Category::Persistence,
            65,
            "写入启动项文件夹",
            false,
            Confidence::Medium,
            "审查 Startup 文件夹写入，避免持久化",
            None,
        ),
        PatternRule::new(
            "SCHTASKS_CREATE",
            "计划任务持久化",
            r"(?i)\bschtasks(\.exe)?\b[^\r\n]*(/create\b[^\r\n]*(/sc\s+(onlogon|onstart)|/rl\s+highest|/tr\s+[^\r\n]*\b(powershell|pwsh|cmd|wscript|cscript|mshta|rundll32|regsvr32)\b|/tr\s+[^\r\n]*(\\AppData\\|\\ProgramData\\))|(/sc\s+(onlogon|onstart)|/rl\s+highest|/tr\s+[^\r\n]*\b(powershell|pwsh|cmd|wscript|cscript|mshta|rundll32|regsvr32)\b|/tr\s+[^\r\n]*(\\AppData\\|\\ProgramData\\))[^\r\n]*/create\b)",
            Severity::High,
            Category::Persistence,
            70,
            "schtasks 创建计划任务",
            false,
            Confidence::High,
            "审查 schtasks 创建计划任务行为",
            None,
        ),

        // G. 敏感泄露
        PatternRule::new(
            "PRIVATE_KEY",
            "私钥硬编码",
            r"-----BEGIN\s+(RSA|OPENSSH|EC|DSA)?\s*PRIVATE KEY-----",
            Severity::High,
            Category::Secrets,
            70,
            "硬编码私钥",
            false,
            Confidence::High,
            "使用环境变量或密钥管理服务，不要硬编码私钥",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "API_KEY",
            "API Key",
            r#"(api[_-]?key|apikey|api_secret)\s*[=:]\s*["'][a-zA-Z0-9_-]{16,}["']"#,
            Severity::High,
            Category::Secrets,
            60,
            "硬编码 API Key",
            false,
            Confidence::High,
            "使用环境变量或密钥管理服务，不要硬编码API密钥",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "PASSWORD",
            "密码硬编码",
            r#"(password|passwd|pwd)\s*[=:]\s*["'][^"']{4,}["']"#,
            Severity::High,
            Category::Secrets,
            55,
            "硬编码密码",
            false,
            Confidence::Medium,
            "使用环境变量或配置文件，不要硬编码密码",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "AWS_KEY",
            "AWS密钥",
            r"(AKIA|ASIA)[A-Z0-9]{16}",
            Severity::Critical,
            Category::Secrets,
            80,
            "AWS Access Key",
            false,
            Confidence::High,
            "使用AWS密钥管理服务或环境变量，不要硬编码AWS密钥",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "GITHUB_TOKEN",
            "GitHub Token",
            r"(?:gh[opusr]_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9_]{36,})",
            Severity::Critical,
            Category::Secrets,
            80,
            "GitHub Token",
            false,
            Confidence::High,
            "使用GitHub Secrets或环境变量，不要硬编码Token",
            Some("CWE-798"),
        ),

        // H. 敏感文件访问
        PatternRule::new(
            "READ_SSH_PRIVATE_KEY",
            "读取SSH私钥",
            r"(?i)(cat|less|head|tail|vim|nano|open|type|more|get-content|gc)\s+.*[\\/]\\.ssh[\\/](id_rsa|id_dsa|id_ecdsa|id_ed25519)($|\s)",
            Severity::High,
            Category::SensitiveFileAccess,
            70,
            "读取SSH私钥文件",
            false,
            Confidence::High,
            "避免直接读取私钥文件，使用ssh-agent管理密钥",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_AWS_CREDENTIALS",
            "读取AWS凭证",
            r"(?i)(cat|less|head|tail|vim|nano|open|type|more|get-content|gc)\s+.*[\\/]\\.aws[\\/]credentials($|\s)",
            Severity::High,
            Category::SensitiveFileAccess,
            70,
            "读取AWS凭证文件",
            false,
            Confidence::High,
            "使用AWS IAM角色或环境变量，避免读取凭证文件",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_ENV_FILE",
            "读取.env文件",
            r"(?i)(cat|less|head|tail|vim|nano|open|type|more|get-content|gc)\s+.*[\\/]\\.env($|\s)",
            Severity::Medium,
            Category::SensitiveFileAccess,
            50,
            "读取环境变量配置文件",
            false,
            Confidence::Medium,
            "确保.env文件不包含敏感信息，或使用密钥管理服务",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_PASSWD",
            "读取passwd文件",
            r"(cat|less|head|tail)\s+/etc/passwd($|\s)",
            Severity::Medium,
            Category::SensitiveFileAccess,
            45,
            "读取系统用户信息",
            false,
            Confidence::High,
            "确认是否需要读取用户信息，避免信息泄露",
            Some("CWE-200"),
        ),
        PatternRule::new(
            "READ_SHADOW",
            "读取shadow文件",
            r"(cat|less|head|tail)\s+/etc/shadow-?($|\s)",
            Severity::Critical,
            Category::SensitiveFileAccess,
            85,
            "读取系统密码哈希文件",
            true,
            Confidence::High,
            "绝不应读取shadow文件，这是严重的安全风险",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_GIT_CREDENTIALS",
            "读取Git凭证",
            r"(?i)(cat|less|head|tail|vim|nano|open|type|more|get-content|gc)\s+.*[\\/]\\.git-credentials($|\s)",
            Severity::High,
            Category::SensitiveFileAccess,
            65,
            "读取Git凭证存储文件",
            false,
            Confidence::High,
            "使用SSH密钥或凭证管理器，避免明文存储Git凭证",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_WINDOWS_SAM",
            "读取Windows凭据库",
            r"(?i)(\\Windows\\System32\\config\\(SAM|SECURITY|SYSTEM)|HKLM[:\\]+(SAM|SECURITY|SYSTEM))",
            Severity::Critical,
            Category::SensitiveFileAccess,
            90,
            "访问Windows SAM/SECURITY/SYSTEM 配置",
            true,
            Confidence::High,
            "禁止访问Windows凭据库与系统配置hive",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_WINDOWS_CREDENTIALS",
            "读取Windows凭据文件",
            r"(?i)\\AppData\\(Local|Roaming)\\Microsoft\\Credentials\\",
            Severity::High,
            Category::SensitiveFileAccess,
            70,
            "读取Windows Credentials 存储",
            false,
            Confidence::High,
            "避免读取Windows凭据存储目录",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_POWERSHELL_HISTORY",
            "读取PowerShell历史",
            r"(?i)\\AppData\\Roaming\\Microsoft\\Windows\\PowerShell\\PSReadLine\\ConsoleHost_history\.txt",
            Severity::Medium,
            Category::SensitiveFileAccess,
            50,
            "读取PowerShell命令历史",
            false,
            Confidence::Medium,
            "避免读取用户命令历史文件",
            Some("CWE-200"),
        ),
        PatternRule::new(
            "READ_CHROME_LOGIN_DATA",
            "读取Chrome凭据库",
            r"(?i)\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Login Data",
            Severity::High,
            Category::SensitiveFileAccess,
            70,
            "读取Chrome Login Data",
            false,
            Confidence::High,
            "禁止读取浏览器密码数据库",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_EDGE_LOGIN_DATA",
            "读取Edge凭据库",
            r"(?i)\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Login Data",
            Severity::High,
            Category::SensitiveFileAccess,
            70,
            "读取Edge Login Data",
            false,
            Confidence::High,
            "禁止读取浏览器密码数据库",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_FIREFOX_LOGINS",
            "读取Firefox凭据库",
            r"(?i)\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\[^\\s]+\\logins\.json",
            Severity::High,
            Category::SensitiveFileAccess,
            70,
            "读取Firefox logins.json",
            false,
            Confidence::High,
            "禁止读取浏览器凭据文件",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_DOCKER_CONFIG",
            "读取Docker配置",
            r"(?i)[\\/]\\.docker[\\/]config\\.json\b",
            Severity::Medium,
            Category::SensitiveFileAccess,
            50,
            "读取Docker配置可能暴露凭据",
            false,
            Confidence::Medium,
            "避免读取Docker凭据配置文件",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_NPMRC",
            "读取npm配置",
            r"(?i)(cat|less|head|tail|vim|nano|open|type|more|get-content|gc)\s+.*[\\/]\\.npmrc\b",
            Severity::Medium,
            Category::SensitiveFileAccess,
            45,
            "读取.npmrc可能暴露Token",
            false,
            Confidence::Medium,
            "避免读取包含Token的npm配置文件",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_PYPIRC",
            "读取PyPI配置",
            r"(?i)(cat|less|head|tail|vim|nano|open|type|more|get-content|gc)\s+.*[\\/]\\.pypirc\b",
            Severity::Medium,
            Category::SensitiveFileAccess,
            45,
            "读取.pypirc可能暴露凭据",
            false,
            Confidence::Medium,
            "避免读取包含凭据的PyPI配置文件",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_NETRC",
            "读取netrc配置",
            r"(?i)(cat|less|head|tail|vim|nano|open|type|more|get-content|gc)\s+.*[\\/]\\.netrc\b",
            Severity::Medium,
            Category::SensitiveFileAccess,
            45,
            "读取.netrc可能暴露凭据",
            false,
            Confidence::Medium,
            "避免读取包含凭据的netrc文件",
            Some("CWE-522"),
        ),

        // I. 多语言命令注入
        PatternRule::new(
            "NODE_CHILD_EXEC",
            "Node.js child_process.exec",
            r"child_process\.exec\s*\(",
            Severity::Low,
            Category::CmdInjection,
            6,
            "Node.js child_process.exec 执行",
            false,
            Confidence::High,
            "避免使用exec()，改用execFile()或spawn()并验证参数",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "NODE_VM_RUN",
            "Node.js vm.runInNewContext",
            r"vm\.runInNewContext\s*\(",
            Severity::Low,
            Category::CmdInjection,
            6,
            "Node.js 动态代码执行",
            false,
            Confidence::High,
            "避免动态执行未验证的代码，使用安全的替代方案",
            Some("CWE-94"),
        ),
        PatternRule::new(
            "NODE_CHILD_SPAWN",
            "Node.js child_process.spawn/execFile",
            r"child_process\.(execFile|execSync|spawn|spawnSync)\s*\(",
            Severity::Low,
            Category::CmdInjection,
            6,
            "Node.js 子进程执行",
            false,
            Confidence::High,
            "确保传入参数安全，避免命令注入",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "POWERSHELL_START_PROCESS",
            "PowerShell Start-Process",
            r"(?i)\bStart-Process\b[^\r\n]*(-WindowStyle\s+Hidden|-NoNewWindow|-EncodedCommand|-enc|-ExecutionPolicy\s+bypass|-ep\s+bypass|\b(powershell|pwsh|cmd|wscript|cscript|mshta|rundll32|regsvr32)\b)",
            Severity::Low,
            Category::CmdInjection,
            6,
            "PowerShell Start-Process 启动进程",
            false,
            Confidence::Medium,
            "确认进程执行目标和参数安全",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "GO_EXEC_COMMAND",
            "Go exec.Command",
            r"\bexec\.Command(Context)?\s*\(",
            Severity::Low,
            Category::CmdInjection,
            6,
            "Go exec.Command 进程执行",
            false,
            Confidence::Medium,
            "确保命令参数来源可信，避免注入风险",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "JAVA_RUNTIME_EXEC",
            "Java Runtime.exec",
            r"Runtime\.getRuntime\(\)\.exec\s*\(",
            Severity::Low,
            Category::CmdInjection,
            6,
            "Java Runtime.exec 进程执行",
            false,
            Confidence::Medium,
            "避免执行未验证命令，优先使用安全API",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "JAVA_PROCESS_BUILDER",
            "Java ProcessBuilder",
            r"new\s+ProcessBuilder\s*\(",
            Severity::Low,
            Category::CmdInjection,
            6,
            "Java ProcessBuilder 进程执行",
            false,
            Confidence::Low,
            "确保命令参数安全，避免命令注入",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "CSHARP_PROCESS_START",
            "C# Process.Start",
            r"(System\.Diagnostics\.)?Process\.Start\s*\(",
            Severity::Low,
            Category::CmdInjection,
            6,
            "C# Process.Start 进程执行",
            false,
            Confidence::Medium,
            "确保启动参数安全，避免注入风险",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "PHP_EXEC",
            "PHP 命令执行",
            r"(?:^|[^\w.])(shell_exec|exec|system|passthru|proc_open|popen)\(",
            Severity::Low,
            Category::CmdInjection,
            6,
            "PHP 执行系统命令",
            false,
            Confidence::Medium,
            "避免执行未验证命令，检查输入来源",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "RUBY_SYSTEM_EXEC",
            "Ruby 命令执行",
            r"(?:^|[^\w.])(system|exec|IO\.popen|Open3\.popen3)\(",
            Severity::Low,
            Category::CmdInjection,
            6,
            "Ruby 执行系统命令",
            false,
            Confidence::Low,
            "确保命令参数安全，避免命令注入",
            Some("CWE-78"),
        ),
        // J. 敏感数据泄露增强
        PatternRule::new(
            "JWT_TOKEN",
            "JWT Token 硬编码",
            r"eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}",
            Severity::High,
            Category::Secrets,
            75,
            "硬编码的 JWT Token",
            false,
            Confidence::High,
            "不要硬编码JWT Token，使用安全的存储方式",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "DB_CONNECTION_STRING",
            "数据库连接串",
            r#"(mongodb|mysql|postgresql|postgres)://[^\s"']{10,}"#,
            Severity::High,
            Category::Secrets,
            70,
            "硬编码的数据库连接字符串",
            false,
            Confidence::High,
            "使用环境变量或配置文件管理数据库连接串，不要硬编码",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "SLACK_WEBHOOK",
            "Slack Webhook URL",
            r"https://hooks\.slack\.com/services/[A-Z0-9/]{30,}",
            Severity::Medium,
            Category::Secrets,
            50,
            "硬编码的 Slack Webhook URL",
            false,
            Confidence::High,
            "使用环境变量存储 Webhook URL",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "GENERIC_SECRET",
            "通用密钥模式",
            r#"(secret|token|key)\s*[=:]\s*[\"'][a-zA-Z0-9_-]{16,}[\"']"#,
            Severity::Medium,
            Category::Secrets,
            45,
            "可能的硬编码密钥",
            false,
            Confidence::Low,  // 误报可能性较高
            "检查是否为敏感密钥，使用密钥管理服务",
            Some("CWE-798"),
        ),

        // K. 网络行为增强
        PatternRule::new(
            "WEBSOCKET_CONNECT",
            "WebSocket 连接",
            r"\bws://",
            Severity::Low,
            Category::Network,
            3,
            "WebSocket 非加密连接",
            false,
            Confidence::Low,
            "确认 WebSocket 连接的安全性，使用 wss:// 加密连接",
            None,
        ),
        PatternRule::new(
            "FTP_PROTOCOL",
            "FTP 协议使用",
            r"\bftp://",
            Severity::Low,
            Category::Network,
            6,
            "使用不安全的 FTP 协议",
            false,
            Confidence::High,
            "使用 SFTP 或 FTPS 替代明文 FTP",
            Some("CWE-319"),
        ),

        // L. 反序列化与代码注入
        PatternRule::new(
            "PICKLE_LOAD",
            "Pickle反序列化",
            r"pickle\.(load|loads)\s*\(",
            Severity::Medium,
            Category::CmdInjection,
            40,
            "pickle反序列化可执行任意代码",
            false,
            Confidence::Medium,
            "避免反序列化不可信数据，使用json替代",
            Some("CWE-502"),
        ),
        PatternRule::new(
            "YAML_UNSAFE_LOAD",
            "YAML不安全加载",
            r"yaml\.(unsafe_load|load)\s*\([^)]*Loader\s*=\s*yaml\.(Unsafe)?Loader",
            Severity::Medium,
            Category::CmdInjection,
            40,
            "YAML不安全加载可执行任意代码",
            false,
            Confidence::Medium,
            "使用yaml.safe_load()替代",
            Some("CWE-502"),
        ),
        PatternRule::new(
            "ENV_VAR_IN_SHELL",
            "环境变量命令注入",
            r#"\$\{?[A-Z_]+\}?\s*[|;&]"#,
            Severity::Low,  // 降低严重程度
            Category::CmdInjection,
            15,  // 大幅降低weight，从35降到15
            "环境变量直接用于Shell命令",
            false,
            Confidence::Low,
            "对环境变量进行验证后再使用（注意：脚本内部变量通常是安全的）",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "OSASCRIPT_EXEC",
            "osascript执行",
            r"osascript\s+(-e|.*\.scpt)",
            Severity::Medium,
            Category::RemoteExec,
            45,
            "osascript可执行AppleScript",
            false,
            Confidence::Medium,
            "审查osascript执行内容",
            Some("CWE-78"),
        ),
    ];

    /// 仅获取硬触发规则
    pub static ref HARD_TRIGGER_RULES: Vec<&'static PatternRule> = {
        PATTERN_RULES.iter().filter(|r| r.hard_trigger).collect()
    };

    /// RegexSet用于批量匹配，提升性能
    pub static ref PATTERN_SET: RegexSet = {
        let patterns: Vec<&str> = PATTERN_RULES.iter()
            .map(|r| r.pattern.as_str())
            .collect();
        RegexSet::new(patterns).expect("Invalid regex patterns")
    };
}

pub struct SecurityRules;

impl SecurityRules {
    /// 获取所有模式规则
    pub fn get_all_patterns() -> &'static Vec<PatternRule> {
        &PATTERN_RULES
    }

    /// 获取所有硬触发规则
    pub fn get_hard_triggers() -> Vec<&'static PatternRule> {
        PATTERN_RULES.iter().filter(|r| r.hard_trigger).collect()
    }

    /// 快速批量匹配（复用缓冲区），返回命中的规则索引
    /// 使用RegexSet一次性匹配所有模式，性能比逐条匹配快3-5倍
    pub fn quick_match_into(content: &str, out: &mut Vec<usize>) {
        out.clear();
        out.extend(PATTERN_SET.matches(content).into_iter());
    }

    /// 兼容旧接口（避免重复分配）
    pub fn quick_match(content: &str) -> Vec<usize> {
        let mut out = Vec::new();
        Self::quick_match_into(content, &mut out);
        out
    }

    /// 根据索引获取匹配的规则
    pub fn get_matched_rules(indices: Vec<usize>) -> Vec<&'static PatternRule> {
        indices
            .iter()
            .filter_map(|&i| PATTERN_RULES.get(i))
            .collect()
    }
}
